project:
  type: website
  output-dir: docs

website:
  title: "CSCI 0451 Blog"
  navbar:
    background: "#090a36"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://linkedin.com

format:
  html:
    title-block-banner: img/tech-background.jpeg
    title-block-banner-color: white
    theme: cosmo
    css: styles.css





